# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d72993dcb89a2f7ca855d631d95d752f9fe81032630357b48060eb09de98f7466973a3438b9f2cbe5672ec4a30fa1aedf6e03935f6c7337bc2bd4a94067af3a

test:
  secret_key_base: 3d641a1cf4c9edcd9ae0d64f9618b5c5332d3f154c42b0c06bca2f1557772d2e1d75be0a452dee70ae7a2bdddfa1174219a5f87d3cc847bb927d15b6bd39aa29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
